export const actioncardMock = {
  type: "prompt",
  id: "EzSeVP0iZ2PSCpTeMadQZ-us|0000001_1",
  messageId: "EzSeVP0iZ2PSCpTeMadQZ-us|0000001",
  text: "Please select one of the following:",
  user: "system",
  title: "Please select one of the following:",
  focus: true,
  date: 1668861995693,
  dateString: new Date(1668861995693).toLocaleTimeString([], { hour: 'numeric', minute: '2-digit' }),
  status: "delivered",
  className: "",
  replyToId: "EzSeVP0iZ2PSCpTeMadQZ-us|0000000",
  buttons: [
    {
      title: "My Benefits",
      type: "button",
      value: "My Benefits",
      selected: false,
      disabled: false,
    },
    {
      title: "My Claims",
      type: "button",
      value: "My Claims",
      selected: false,
      disabled: false,
    },
    {
      title: "Other Admin. Resources",
      type: "button",
      value: "Other Admin. Resources",
      selected: false,
      disabled: false,
    },
    {
      title: "Something Else",
      type: "button",
      value: "Something Else",
      selected: false,
      disabled: false,
    },
  ],
  active: true,
};
