import { GetMessagesType, SendMessageType, SendSessionType, EndSessionType, DownloadTranscript,SurveyType, surveyTokenAPI, surveyLinkAPI } from './interfaces';

const ActionSetSurvey: SurveyType = {
    SET_SURVEY_LINK: "SET_SURVEY_LINK",
    SET_SURVEY_ERROR: "SET_SURVEY_ERROR",
    SET_SURVEY_TOKEN: "SET_SURVEY_TOKEN",
    SET_SURVEY: "SET_SURVEY",
    SET_SURVEY_CONFIG: 'SET_SURVEY_CONFIG',
    SET_SURVEY_USER: 'SET_SURVEY_USER',
    SET_SURVEY_LOADING:"SET_SURVEY_LOADING"
    
}

const ActionGetMessages: GetMessagesType = {
    GET_MESSAGES: "GET_MESSAGES",
    GET_COUNT: "GET_COUNT",
    SENT_MESSAGE: "SENT_MESSAGE",
    SENT_MESSAGE_ERROR: "SENT_MESSAGE_ERROR"
}

const ActionSetSession: SendSessionType = {
    SET_SESSION: "SET_SESSION",
    SET_SESSION_ID: "SET_SESSION_ID",
    SET_MODAL_TYPE: "SET_MODAL_TYPE",
    SET_SESSION_ENDED: "SET_SESSION_ENDED",
    SET_SHOW_TIMEOUT_MODAL: "SET_SHOW_TIMEOUT_MODAL",
    SET_TIMED_OUT: "SET_TIMED_OUT",
    SET_SESSION_ENDED_BY_USER: "SET_SESSION_ENDED_BY_USER",
    SET_SESSION_ENDED_BY_BOT: "SET_SESSION_ENDED_BY_BOT",
    SET_SESSION_ENDED_BY_AGENT: "SET_SESSION_ENDED_BY_AGENT",
    SET_WAITING_FOR_AGENT: "SET_WAITING_FOR_AGENT",
    SET_SHOW_AGENT_TYPING: "SET_SHOW_AGENT_TYPING",
    SET_CONNECTED_WITH_AGENT: "SET_CONNECTED_WITH_AGENT",
    SET_SESSION_ATTRIBUTES: "SET_SESSION_ATTRIBUTES",
    SET_SESSION_TRANSFER: "SET_SESSION_TRANSFER",
    SET_TRANSFER_TYPE:"SET_TRANSFER_TYPE",
    SET_GLOBAL_PHONE_1800: "SET_GLOBAL_PHONE_1800",
    SET_GLOBAL_PHONE_LOCAL: "SET_GLOBAL_PHONE_LOCAL",
    SET_SHOW_LOADING:"SET_SHOW_LOADING",
    SET_MESSAGE_LOADING:"SET_MESSAGE_LOADING",
    SET_AGENT_REQUEST_CANCELED: "SET_AGENT_REQUEST_CANCELED",
    SET_TIMEOUT_SECONDS:"SET_TIMEOUT_SECONDS",
    SET_FOCUS: "SET_FOCUS",
}

const ActionSendMessage: SendMessageType = {
    SEND_MESSAGES: "SEND_MESSAGES"
}

const ActionEndSession: EndSessionType = {
    END_SESSION: "END_SESSION"
}

const ActionDownloadTranscript: DownloadTranscript = {
    DOWNLOAD_MESSAGE: "DOWNLOAD_MESSAGE"
}

const ActionSurveyTokenAPI: surveyTokenAPI = {
    SURVEY_TOKEN_API: "SURVEY_TOKEN_API"
}

const ActionSurveyLinkAPI: surveyLinkAPI = {
    SURVEY_LINK_API: "SURVEY_LINK_API",
    SURVEY_SEARCH_API: "SURVEY_SEARCH_API",
    SET_SURVEY_ATTRIBUTES: "SET_SURVEY_ATTRIBUTES",
}
export default { ActionGetMessages, ActionSendMessage, ActionSetSession, ActionEndSession, ActionDownloadTranscript ,ActionSetSurvey,ActionSurveyTokenAPI,ActionSurveyLinkAPI};
